version: "3.9"
services: 
  postgres:
    image: postgres:15.0-alpine
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=stori_db
    ports:
      - "5432:5432"
      
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-d", "db_prod"]
      interval: 30s
      timeout: 60s
      retries: 5
      start_period: 80s  
  
  api:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - DB_HOST=postgres
      - DB_USER=root
      - DB_PASSWORD=secret
      - DB_NAME=stori_db
      - DB_PORT=5432
      - DB_SSLMODE=disable
      - EMAIL_HOST=bulk.smtp.mailtrap.io 
      - EMAIL_PORT=587
      - EMAIL_USER=api
      - EMAIL_PASSWORD=06a5dbcc0b6a31b96285e338dd500f2b#2bf0a481a09bb7 

    depends_on:
      postgres:
        condition: service_healthy
