version: "3.9"
services: 
  postgres:
    image: postgres:15.0-alpine
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=stori_db
    ports:
      - "5432:5432"
      
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-d", "db_prod"]
      interval: 30s
      timeout: 60s
      retries: 5
      start_period: 80s  
  
  # api:
  #   build: 
  #     context: .
  #     dockerfile: Dockerfile
  #   ports:
  #     - "8000:8000"
  #   environment:
  #     - DB_SOURCE=postgresql://root:secret@postgres:5432/stori_db?sslmode=disable

  #   depends_on:
  #     postgres:
  #       condition: service_healthy
