// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.24.0
// source: transfer.sql

package sqlc_code

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createTransfer = `-- name: CreateTransfer :one
INSERT INTO transfers (
  amount,
  reason,
  account_id
) VALUES (
  $1, $2, $3
) RETURNING id, amount, reason, account_id
`

type CreateTransferParams struct {
	Amount    float64
	Reason    pgtype.Text
	AccountID pgtype.Int4
}

func (q *Queries) CreateTransfer(ctx context.Context, arg CreateTransferParams) (Transfer, error) {
	row := q.db.QueryRow(ctx, createTransfer, arg.Amount, arg.Reason, arg.AccountID)
	var i Transfer
	err := row.Scan(
		&i.ID,
		&i.Amount,
		&i.Reason,
		&i.AccountID,
	)
	return i, err
}

const getTransfer = `-- name: GetTransfer :one
SELECT id, amount, reason, account_id FROM transfers
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetTransfer(ctx context.Context, id int32) (Transfer, error) {
	row := q.db.QueryRow(ctx, getTransfer, id)
	var i Transfer
	err := row.Scan(
		&i.ID,
		&i.Amount,
		&i.Reason,
		&i.AccountID,
	)
	return i, err
}

const listTransfers = `-- name: ListTransfers :many
SELECT id, amount, reason, account_id FROM transfers
WHERE 
    account_id = $1
ORDER BY id
LIMIT $2
OFFSET $3
`

type ListTransfersParams struct {
	AccountID pgtype.Int4
	Limit     int32
	Offset    int32
}

func (q *Queries) ListTransfers(ctx context.Context, arg ListTransfersParams) ([]Transfer, error) {
	rows, err := q.db.Query(ctx, listTransfers, arg.AccountID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Transfer
	for rows.Next() {
		var i Transfer
		if err := rows.Scan(
			&i.ID,
			&i.Amount,
			&i.Reason,
			&i.AccountID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
